# local
spring.config.activate.on-profile: local
logging.config: classpath:logback/logback-local.xml

---
# dev
spring.config.activate.on-profile: dev
logging.config: classpath:logback/logback-dev.xml

---
# live
spring.config.activate.on-profile: live
logging.config: classpath:logback/logback-live.xml