# local
spring.config.activate.on-profile: local

management: # Actuator
  endpoints:
    enabled-by-default: false # default 사용하지 않을 것
    jmx: # JMX 형태 사용 불가 처리
      exposure:
        exclude: '*'
    web:
      base-path: /one-baily-actuator # Actuator 경로 변경
      exposure:
        include: metrics, prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  # actuator 포트 변경
  server:
    port: ${MANAGEMENT_PORT:7463}
---
# dev
spring.config.activate.on-profile: dev

management: # Actuator
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: '*'
    web:
      base-path: /one-baily-actuator
      exposure:
        include: metrics, prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  server:
    port: ${MANAGEMENT_PORT:7463}
---
# live
spring.config.activate.on-profile: live

management: # Actuator
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: '*'
    web:
      base-path: /one-baily-actuator
      exposure:
        include: metrics, prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  server:
    port: ${MANAGEMENT_PORT:7463}
