# default
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

---
# local
spring.config.activate.on-profile: local

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(EuTWOejZ/TVxzVr8BuOraMUtzqHbSrMmVbG8i3sxaegIAOHHfwvm3dLHGDpJMVmQE8GHC9wablsS370aoZEZZg==)
    username: ENC(y6jFI+0DMaRvoUW962oCyg==)
    password: ENC(cuWaUt+8bNMAV6aLO4GMaw==)
    hikari:
      pool-name: db-core-pool
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
---
# dev
spring.config.activate.on-profile: dev

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(EuTWOejZ/TVxzVr8BuOraMUtzqHbSrMmVbG8i3sxaegIAOHHfwvm3dLHGDpJMVmQE8GHC9wablsS370aoZEZZg==)
    username: ENC(y6jFI+0DMaRvoUW962oCyg==)
    password: ENC(cuWaUt+8bNMAV6aLO4GMaw==)
    hikari:
      pool-name: db-core-pool


---
# live
spring.config.activate.on-profile: live

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(jnA7eWlf1zdjW5d2Flm/8ZetYCGTR3wkTE7Wk7NdJWJK9XZmcSNO300/VHhHG04tUQlf4nq5sbc6ShvOF1MV+A==)
    username: ENC(ORiZUOmorrTYkZUUCqHN8g==)
    password: ENC(A6Ii6Iq/etslKSo3kRcS0g==)
    hikari:
      pool-name: db-core-pool