# local
spring.config.activate.on-profile: local
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
        registration:
          naver:
            redirect-uri: http://localhost:8080/dev/api/login/oauth2/code/naver
            client-id: ENC(qFYukOWHaCGpavvnBwIIe5MfIbMaETjo8ABJPEvKL1o=)
            client-secret: ENC(sJK/TYU3PJj1+d6mB1OXjZTrmUFdALuC)
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
            client-name: naver
          kakao:
            redirect-uri: http://localhost:8080/dev/api/login/oauth2/code/kakao
            client-id: ENC(nUuzK5Tc/0XQDn0AWm3DlNjzZaLxUPzh9ujSdPot9wrOnA1Cmgl1eLyWMyIpI/P0)
            authorization-grant-type: authorization_code
            scope:
              - profile_image
              - account_email
            client-name: kakao
          google:
            redirect-uri: http://localhost:8080/dev/api/login/oauth2/code/google
            client-id: ENC(v6CCXncJwOS8W6YizTBkDskIbDrBV/DM+1WpJvERtF6YUahSyevhaoxPQxkdy3DXK++9NZMP7OeqRi7qhgRizQNjXD+u2hNIxIcWu6B71fATnGojMqiDEg==)
            client-secret: ENC(Sv6L3GpxMxJA7s93BGorm6DclzLwJYSg8rezWXhkAi0PY85zzA/d7ulKspstKMY/)
            scope:
              - email
              - profile