# dev
spring.config.activate.on-profile: dev

server:
  port: 8888
  servlet:
    context-path: /dev/api

spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
        registration:
          naver:
            redirect-uri: ENC(4+bYmAkIEVrVaxN+PJN45Yw4OX+7ic6kI++xBfdUrAQue4vWC1apiXgr+jIHrd1/IIFxyyNHSzDYjxMT89gBjaIGUPuhX3lZ)
            client-id: ENC(qFYukOWHaCGpavvnBwIIe5MfIbMaETjo8ABJPEvKL1o=)
            client-secret: ENC(sJK/TYU3PJj1+d6mB1OXjZTrmUFdALuC)
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
            client-name: naver
          kakao:
            redirect-uri: ENC(cNaBf93iYsA00MQEQfTGWEsp7iDqUMwuMKzYg6XHjZ9X8CfegTlRidbSrMC67R73zy3BnKfjBmTtJzin8iowfaww+J8WqD6n)
            client-id: ENC(LzuIWpuN7JG7pwbU87S4DvColRj57LtcnRb0qfDdyGpnNUpI2+FHgCyJs0p2Wn7/)
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
            client-name: kakao
          google:
            redirect-uri: ENC(+n1rnKqq7yRkybeNRGFstgM1rZcE84mn/3eHn86kNkjcZYmOtHO4h0CYCAsnIeA1aw8TaGRpqAIDSKx0F0ah7PeiUD+Shkr9)
            client-id: ENC(v6CCXncJwOS8W6YizTBkDskIbDrBV/DM+1WpJvERtF6YUahSyevhaoxPQxkdy3DXK++9NZMP7OeqRi7qhgRizQNjXD+u2hNIxIcWu6B71fATnGojMqiDEg==)
            client-secret: ENC(Sv6L3GpxMxJA7s93BGorm6DclzLwJYSg8rezWXhkAi0PY85zzA/d7ulKspstKMY/)
            scope:
              - email
              - profile