# local
spring.config.activate.on-profile: test

server:
  port: 8080
  servlet:
    context-path: /dev/api

apple-login:
  url: https://appleid.apple.com
  key-path: EMPTY-VALUE
  client-id: EMPTY-VALUE
  team-id: EMPTY-VALUE
  key-id: EMPTY-VALUE

redirect-url:
  live: ENC(n7sXFCoABK2wVGKkMdhVLJEtvfHXtds+NwvpxWntSnYArf3DGN2cFbKlCR9hIACj)
  dev: ENC(ZOWsz9hwBfF4yJrxHevHshhkGZqYuS9XyoFFLQQea473KOSJoKg2zMgHOGXkoGGz8jZ3Zc4rnQE=)
  local: ENC(LxpM8W1yvAXRpin++amkeEhqGXro90Y2E3tQgD4EzOJnOZfBVKST3TF/0T3CqvZZ)

spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?scope=name%20email&response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
        registration:
          naver:
            redirect-uri: http://localhost:8080/dev/api/login/oauth2/code/naver
            client-id: EMPTY-VALUE
            client-secret: EMPTY-VALUE
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
            client-name: naver
          kakao:
            redirect-uri: http://localhost:8080/dev/api/login/oauth2/code/kakao
            client-id: EMPTY-VALUE
            authorization-grant-type: authorization_code
            scope:
              - profile_image
              - account_email
            client-name: kakao
          google:
            redirect-uri: http://localhost:8080/dev/api/login/oauth2/code/google
            client-id: EMPTY-VALUE
            client-secret: EMPTY-VALUE
            scope:
              - email
              - profile
          apple:
            client-id: EMPTY-VALUE
            client-secret: EMPTY-VALUE
            redirect-uri: EMPTY-VALUE
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: POST
            clientName: pple
            scope:
              - email
              - name