# local
spring.config.activate.on-profile: local
server:
  port: 8080
  servlet:
    context-path: /api

apple-login:
  url: https://appleid.apple.com
  key-path: ENC(gx6Kp/2mu6h1YLa5RIJw+IT1uVig/jK8zAv0ZJzQNrWKGkIIcgQod3UhWZujYuuY)
  client-id: ENC(j8Pv9pV9xD3oBKDsElXTedl2UrtAGMx13RpJ9NRDVH4=)
  team-id: ENC(jzk4UvjfcLerYSo05oJ8vNGGxgt4SLuS)
  key-id: ENC(T/yX80PVdBkgQcFkOs/H2dFgAuBKDeNR)

redirect-url:
  live: ENC(n7sXFCoABK2wVGKkMdhVLJEtvfHXtds+NwvpxWntSnYArf3DGN2cFbKlCR9hIACj)
  dev: ENC(ZOWsz9hwBfF4yJrxHevHshhkGZqYuS9XyoFFLQQea473KOSJoKg2zMgHOGXkoGGz8jZ3Zc4rnQE=)
  local: ENC(LxpM8W1yvAXRpin++amkeEhqGXro90Y2E3tQgD4EzOJnOZfBVKST3TF/0T3CqvZZ)


spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?scope=name%20email&response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
        registration:
          naver:
            redirect-uri: http://localhost:8080/dev/api/login/oauth2/code/naver
            client-id: ENC(qFYukOWHaCGpavvnBwIIe5MfIbMaETjo8ABJPEvKL1o=)
            client-secret: ENC(sJK/TYU3PJj1+d6mB1OXjZTrmUFdALuC)
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
            client-name: naver
          kakao:
            redirect-uri: http://localhost:8080/dev/api/login/oauth2/code/kakao
            client-id: ENC(nUuzK5Tc/0XQDn0AWm3DlNjzZaLxUPzh9ujSdPot9wrOnA1Cmgl1eLyWMyIpI/P0)
            authorization-grant-type: authorization_code
            scope:
              - profile_image
              - account_email
            client-name: kakao
          google:
            redirect-uri: http://localhost:8080/dev/api/login/oauth2/code/google
            client-id: ENC(v6CCXncJwOS8W6YizTBkDskIbDrBV/DM+1WpJvERtF6YUahSyevhaoxPQxkdy3DXK++9NZMP7OeqRi7qhgRizQNjXD+u2hNIxIcWu6B71fATnGojMqiDEg==)
            client-secret: ENC(Sv6L3GpxMxJA7s93BGorm6DclzLwJYSg8rezWXhkAi0PY85zzA/d7ulKspstKMY/)
            scope:
              - email
              - profile
          apple:
            client-id: ENC(j8Pv9pV9xD3oBKDsElXTedl2UrtAGMx13RpJ9NRDVH4=)
            client-secret: ENC(gx6Kp/2mu6h1YLa5RIJw+IT1uVig/jK8zAv0ZJzQNrWKGkIIcgQod3UhWZujYuuY)
            redirect-uri: ENC(2YqEJV59zerpIc6IHl+DZuQIrtlbWWJ7WB5//o19st3Nm46pQJ0gh0XG4127p2oVWjpLhgeLjyzm3Jgw5CWa34K1WEjWlEWX)
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: POST
            clientName: Apple
            scope:
              - email
              - name