# dev
spring.config.activate.on-profile: dev

server:
  port: 8888
  servlet:
    context-path: /dev/api

spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
        registration:
          naver:
            redirect-uri: ${NAVER-REDIRECT-URI}
            client-id: ${NAVER-CLIENT-ID}
            client-secret: ${NAVER-CLIENT-SECRET}
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
            client-name: naver
          kakao:
            redirect-uri: ${KAKAO-REDIRECT-URI}
            client-id: ${KAKAO-CLIENT-ID}
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_image
            client-name: kakao
          google:
            redirect-uri: ${GOOGLE-REDIRECT-URI}
            client-id: ${GOOGLE-CLIENT-ID}
            client-secret: ${GOOGLE-CLIENT-SECRET}
            scope:
              - email
              - profile