# local
spring.config.activate.on-profile: test

server:
  port: 8080
  servlet:
    context-path: /dev/api

spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
        registration:
          naver:
            redirect-uri: http://localhost:8080/dev/api/login/oauth2/code/naver
            client-id: EMPTY-VALUE
            client-secret: EMPTY-VALUE
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
            client-name: naver
          kakao:
            redirect-uri: http://localhost:8080/dev/api/login/oauth2/code/kakao
            client-id: EMPTY-VALUE
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
            client-name: kakao
          google:
            redirect-uri: http://localhost:8080/dev/api/login/oauth2/code/google
            client-id: EMPTY-VALUE
            client-secret: EMPTY-VALUE
            scope:
              - email
              - profile