spring.config.activate.on-profile: live

server:
  port: 8080
  servlet:
    context-path: /live/api
  forward-headers-strategy: framework


apple-login:
  url: https://appleid.apple.com
  key-path: ENC(gx6Kp/2mu6h1YLa5RIJw+IT1uVig/jK8zAv0ZJzQNrWKGkIIcgQod3UhWZujYuuY)
  client-id: ENC(j8Pv9pV9xD3oBKDsElXTedl2UrtAGMx13RpJ9NRDVH4=)
  team-id: ENC(jzk4UvjfcLerYSo05oJ8vNGGxgt4SLuS)
  key-id: ENC(T/yX80PVdBkgQcFkOs/H2dFgAuBKDeNR)

spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?scope=name%20email&response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
        registration:
          naver:
            redirect-uri: ENC(MQq1obaTDXs7LryM3+BOdHMrQcs/zibSLKHoPst/H6swX8Dpvl7Wo+XBW+SGaMq37aJZyQ9+pqcyYuUIPABg4l/4I2JBKQ4V)
            client-id: ENC(hArDuXel6XL2BYuka4j5o+PuFa9OYb1kIs9ZWjiRCYs=)
            client-secret: ENC(eJBwzFm1mur/BHJjlPHw2Gh9vLP/6RY4)
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
            client-name: naver
          kakao:
            redirect-uri: ENC(ZWbt0nXnT8j9h3IkHegdUWlFq/4ar6fxHgcNbZc616y/XE6mxkk5c3uLI7/1SaeRQzvwrauIQHXFat/u/juy6AfRQ9fMqQMP)
            client-id: ENC(BYrtro2a1mPMV3yGyXZL03KEbrk6XhKG4oz9c4oX88TJzPNlzpAmSwC6xBLVl9aZ)
            authorization-grant-type: authorization_code
            scope:
              - profile_image
              - account_email
            client-name: kakao
          google:
            redirect-uri: ENC(S1UGPrXcnpwpjOsa4copqhtLQFReKF9JvPhh3PqImrWxj7BRS6DBAvwkhv80pJrW6NK+nGVGLcZC4sdCPqvdn7dhgXHegEwn)
            client-id: ENC(KNctPOIqjyR4vPOkN2pJtdu4P70tiAnOHndfQp9HC+qZLx/XdBXLMNNKvjlLBJ4Yh0D6UI5z7RFP83MsfLW16o0K5LFDDmchCsyW2ShmQiAoeNN29W7Ptw==)
            client-secret: ENC(3+GdJBjiGpBabKBY1/Ipw57ddI30By/3LYMoQzjbDbnp3dsiTsvvndEJRZXRQpTk)
            scope:
              - email
              - profile
          apple:
            client-id: ENC(j8Pv9pV9xD3oBKDsElXTedl2UrtAGMx13RpJ9NRDVH4=)
            client-secret: ENC(gx6Kp/2mu6h1YLa5RIJw+IT1uVig/jK8zAv0ZJzQNrWKGkIIcgQod3UhWZujYuuY)
            redirect-uri: ENC(5fsttdDarZS472FewZASTFFeYrjAssJic9XYwpKEiWfA0QO26GPpggQX+p7Rqj9/JZi/ABWSor6/6/1aVFRCY3/AFWmozrvU)
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: POST
            clientName: Apple
            scope:
              - email
              - name

