# default
spring:
  profiles:
    default: local
  application:
    name: api
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false

server:
  servlet:
    context-path: /api


springdoc:
  server:
    url: ${SPRINGDOC-SERVER-URL:http://localhost:8080/api}

---
# local
spring:
  profiles:
    group:
      local:
        - security
        - db-core
        - logging
        - metrics

---
# dev
spring:
  profiles:
    group:
      dev:
        - security
        - db-core
        - logging
        - metrics

---
# live
spring:
  profiles:
    group:
      live:
        - security
        - db-core
        - logging
        - metrics