# local
spring.config.activate.on-profile: local

server:
  port: 8080
  servlet:
    context-path: /dev/api

spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
        registration:
          naver:
            client-id: ENC(/qzOXwuIXc/q0hiutk6qaxqy7KEZpTOPnWAXWMOiQlk=)
            client-secret: ENC(JCO+cy8kcGWUnbzEz5fYPwEgvX9dkxvh)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
            client-name: naver
          kakao:
            client-id: ENC(exKGui32ds6bUGVLSDwbMBXK+4SSb4GoFkDUBpzfchrlOQBCym996oRTuXaiqhG7)
            redirect-uri: http://localhost:8080/api/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
            client-name: kakao
          google:
            redirect-uri: ENC(gPNzZWCUREOBhkgzyIDnZqzofQchy9+DH9EoVoxYz+fpxUUndX0TO+RwIirLdTCXQaATBp/TM/ECxIyez4uZFg==)
            client-id: ENC(TucLQq2mg5X0ts97rLtncbn0d2OtGal96/sgltZqpq65sd0JLkU2hn74UON+g/NWnRV+CmF+XlOmYLcR9B2mSKcNssPLEo+nT1CvYhSvlh+0cefiMY4HnQ==)
            client-secret: ENC(rRTLtapxD65ZIfQXx4TFl3/ScyGWmHMYZoDyWygUxQbFS58E3dQHLrrBLuJvKDKH)
            scope:
              - email
              - profile


---
# dev
spring.config.activate.on-profile: dev

server:
  port: 8888
  servlet:
    context-path: /dev/api

spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
        registration:
          naver:
            client-id: ENC(/qzOXwuIXc/q0hiutk6qaxqy7KEZpTOPnWAXWMOiQlk=)
            client-secret: ENC(JCO+cy8kcGWUnbzEz5fYPwEgvX9dkxvh)
            redirect-uri: ENC(Cw6GxB7zBSF6IVfUp9bKU54Q7gMXDsuQlzmbVXZLWex1rmvfPljgVZZ5oezX7BaObrpKkPNilBUeIhENX95TdoR6znN9o8jU)
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
            client-name: naver
          kakao:
            client-id: ENC(exKGui32ds6bUGVLSDwbMBXK+4SSb4GoFkDUBpzfchrlOQBCym996oRTuXaiqhG7)
            redirect-uri: ENC(JTUuGtP2xFa4TUcJVlRK0S8Dh7p90pTNoRdWS6jgAtsh0Yv46v5heaNFS6iynM7ujzPT9y0ov8ZOj/2efmktE80XzfySGpO0)
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
            client-name: kakao
          google:
            redirect-uri: ENC(K0htibbNu6hcr/9RyD0O4LM9lzX0q5o4apyH1Ct2lejuEcSi0/1W85SwK6JHEm3XMos3oZ3k/iPzIssnEs6FxOHILa91kimd))
            client-id: ENC(TucLQq2mg5X0ts97rLtncbn0d2OtGal96/sgltZqpq65sd0JLkU2hn74UON+g/NWnRV+CmF+XlOmYLcR9B2mSKcNssPLEo+nT1CvYhSvlh+0cefiMY4HnQ==)
            client-secret: ENC(rRTLtapxD65ZIfQXx4TFl3/ScyGWmHMYZoDyWygUxQbFS58E3dQHLrrBLuJvKDKH)
            scope:
              - email
              - profile

---
# live
spring.config.activate.on-profile: live

server:
  port: 8080
  servlet:
    context-path: /live/api

spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
        registration:
          naver:
            client-id: ENC(/qzOXwuIXc/q0hiutk6qaxqy7KEZpTOPnWAXWMOiQlk=)
            client-secret: ENC(JCO+cy8kcGWUnbzEz5fYPwEgvX9dkxvh)
            redirect-uri: ENC(7mjnpwX/1lXB/8aDVOpbRF/uaR2Wb9MmYKjmGwFzUHaUUJrRwDL17WfCVrYhCyMDDSzPktD5Y7K2KTHq65vvjLpPfmcBrVa+)
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
            client-name: naver
          kakao:
            client-id: ENC(exKGui32ds6bUGVLSDwbMBXK+4SSb4GoFkDUBpzfchrlOQBCym996oRTuXaiqhG7)
            redirect-uri: ENC(EChBZKXGBtXOrm/aHJYBVPaE0xE4yDEje9Hakyd0yadQze4z3lJb/J9U7hdUu7/Ne7LyDE5JleyQPtWY0eq4GamNTLhffVgz)
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
            client-name: kakao
          google:
            redirect-uri: ENC(9+ZtWCwp71Xny9VBtunmmmabG6ACktT43tcVSFSHtI1R/RCLVwLsgG/TgRJ1VN8tqKyYqSF5GOhUKAwYaCprufgbBh7ISod5)
            client-id: ENC(TucLQq2mg5X0ts97rLtncbn0d2OtGal96/sgltZqpq65sd0JLkU2hn74UON+g/NWnRV+CmF+XlOmYLcR9B2mSKcNssPLEo+nT1CvYhSvlh+0cefiMY4HnQ==)
            client-secret: ENC(rRTLtapxD65ZIfQXx4TFl3/ScyGWmHMYZoDyWygUxQbFS58E3dQHLrrBLuJvKDKH)
            scope:
              - email
              - profile

